version: "3"
services:
    jobmanager:
      image: flink:1.16
      expose:
        - "{{inner_port}}"
      ports:
        - "{{inner_port}}:6123"
        - "{{web_port}}:8081"
      command: jobmanager
      environment:
        - JOB_MANAGER_RPC_ADDRESS=jobmanager

    taskmanager:
      image: flink:1.16
      expose:
        - "6121"
        - "6122"
      depends_on:
        - jobmanager
      command: taskmanager
      links:
        - "jobmanager:jobmanager"
      deploy:
        resources:
          limits:
            cpus: "{{cpu}}"
      environment:
        - |
          FLINK_PROPERTIES=
          jobmanager.rpc.address: jobmanager
          parallelism.default: 2
          taskmanager.memory.managed.size: 0
          taskmanager.memory.task.heap.size: {{mem}}
