version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    user: root
    ports:
      - "9091:9091"

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"